bert-base-multilingual-cased: https://huggingface.co/bert-base-multilingual-cased

Notes: does not recognize negatives, max token length is 512, which is less than other models. Does not work for paragraphs.

In [37]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
model = BertModel.from_pretrained("bert-base-multilingual-cased")

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [20]:
text1 = ["Ginger helps cure cancer."]
encoded_input1 = tokenizer(text1, return_tensors='pt')
output1 = model(**encoded_input1)

text2 = ["Ingver aitab ravida vähki."]
encoded_input2 = tokenizer(text2, return_tensors='pt')
output2 = model(**encoded_input2)

text3 = ["Ingver ei aita ravida vähki."]
encoded_input3 = tokenizer(text3, return_tensors='pt')
output3 = model(**encoded_input3)

In [34]:
import torch

npout1 = torch.tensor(output1[1][0]).numpy()
npout2 = torch.tensor(output2[1][0]).numpy()
npout3 = torch.tensor(output3[1][0]).numpy()

C:\Users\LI\AppData\Local\Temp\ipykernel_16044\2320419056.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  npout1 = torch.tensor(output1[1][0]).numpy()
C:\Users\LI\AppData\Local\Temp\ipykernel_16044\2320419056.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  npout2 = torch.tensor(output2[1][0]).numpy()
C:\Users\LI\AppData\Local\Temp\ipykernel_16044\2320419056.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  npout3 = torch.tensor(output3[1][0]).numpy()


In [35]:
# Ginger helps cure cancer. + Ingver aitab ravida vähki.

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

vectors_matrix1 = np.array([npout1, npout2])

similarity_matrix1 = cosine_similarity(vectors_matrix1)

print("Cosine Similarity Matrix:")
print(similarity_matrix1)

Cosine Similarity Matrix:
[[1.0000001  0.92852294]
 [0.92852294 1.0000001 ]]


In [33]:
# Ginger helps cure cancer. + Ingver ei aita ravida vähki.

vectors_matrix2 = np.array([npout1, npout3])

similarity_matrix2 = cosine_similarity(vectors_matrix2)

print("Cosine Similarity Matrix:")
print(similarity_matrix2)

Cosine Similarity Matrix:
[[1.0000001  0.93704706]
 [0.93704706 0.9999998 ]]


Additional testing with paragraphs.

In [39]:
# this model has a maximum token length of 512, which is less than the other models

# first paragraph from snippet
# second, snippet translated to eng
# third, eng snippet text shuffled
# fourth, unrelated parangraph

first = "Olgugi et Tallinna Halduskohus on tunnistanud vaktsiinisunni kaitseväes õigusvastaseks, toonitas Martin Herem kõigile kaitseväe teenistujatele saadetud kirjas, et koroonavaktsiinide manustamine on jätkuvalt teenistuse jätkamise eelduseks ehk kõik teenistujad, kes ei lase endale uut vaktsiinidoosi süstida, peavad kaitseväest lahkuma. Kaitseväe juhataja Martin Herem saatis 6. oktoobril kaitseväe siselisti kaudu laiali kirja, milles informeeris kõiki alluvaid oma otsusest nõuda kõigilt kaitseväe teenistujatelt jätkuvalt Covid-19 vaktsiinide manustamist teenistuse jätkamise eeldusena. Kuigi Tallinna Halduskohus tunnistas oma 30. augusti otsusega vaktsineerimiskohustusele mitteallunud kaitseväe teenistujate ametist vabastamise õigusvastaseks, annab Herem koha oma kirja pealkirjas teada, et kaitsevägi nõuab endiselt vaktsineerimistõendi esitamist. Kohe kirja alguses kinnitab Herem, et kaitseväe juhtkonnal ei ole kavatsust vaktsineerimiskohustusest loobuda."
second = "Even though the Tallinn Administrative Court has recognized forced vaccination in the defense forces as illegal, Martin Herem stressed in a letter sent to all servicemen of the defense forces that the administration of corona vaccines is still a prerequisite for continued service, i.e. all servicemen who do not allow themselves to be injected with a new vaccine dose must leave the defense forces. The head of the defense forces Martin Herem sent On October 6, a letter was distributed through the internal list of the defense forces, in which they informed all subordinates of their decision to continue to demand the administration of Covid-19 vaccines from all servicemen of the defense forces as a prerequisite for continuing their service. Although the Tallinn Administrative Court recognized with its August 30 decision dismissal of defense force personnel who are not subject to the vaccination obligation to be unlawful, gives In the title of his letter, Herem states that the defense force still requires proof of vaccination. Right at the beginning of the letter, Herem confirms that the leadership of the defense force has no intention of abandoning the vaccination obligation."
third = "Despite the Tallinn Administrative Court rejecting the notion of forced vaccination being unlawful in the defense forces, Martin Herem emphasized in a letter addressed to all servicemen that the corona vaccine administration remains a vital requirement for ongoing service. In other words, servicemen who refuse the new vaccine dose injection must exit the defense forces. On October 6, the head of the defense forces, Martin Herem, distributed a letter through the internal list of the defense forces, notifying subordinates of their decision to persist in demanding Covid-19 vaccine administration from all servicemen as a condition for continuing their service. Although the Tallinn Administrative Court dismissed the dismissal of defense force personnel not obligated to vaccination on August 30, Herem's letter insists that the defense force still requires proof of vaccination. At the commencement of the letter, Herem affirms the leadership's unwavering commitment to the vaccination obligation. The Defense Forces has required a valid proof of vaccination against COVID-19 from its servicemen. This requirement is still valid today."
fourth = "Amidst the vibrant tapestry of a bustling cityscape, the echoes of life intertwine with the rhythm of urban existence. In the heart of this metropolis, diverse communities coalesce, each with its narrative, a mosaic of stories that collectively shape the city's identity. From the towering skyscrapers that pierce the heavens to the intimate alleys that harbor hidden gems, every corner pulsates with the energy of human endeavor. Street vendors peddle their wares, filling the air with the aroma of exotic spices and the melody of bargaining. Parks and squares serve as communal canvases, where artists paint the aspirations and reflections of a multifaceted society. As day surrenders to night, the city transforms into a spectacle of lights, a nocturnal ballet choreographed by the ebb and flow of its denizens. Amid the ceaseless motion, moments of stillness emerge — a solitary figure reading a book on a park bench, a street musician serenading passersby, or a couple sharing a quiet conversation in a dimly lit cafe."

In [40]:
# this model has a maximum token length of 512, so I cut the texts in half compared to other models

encoded_input1 = tokenizer(first, return_tensors='pt')
output1 = model(**encoded_input1)

encoded_input2 = tokenizer(second, return_tensors='pt')
output2 = model(**encoded_input2)

encoded_input3 = tokenizer(third, return_tensors='pt')
output3 = model(**encoded_input3)

encoded_input4 = tokenizer(fourth, return_tensors='pt')
output4 = model(**encoded_input4)

npout1 = torch.tensor(output1[1][0]).numpy()
npout2 = torch.tensor(output2[1][0]).numpy()
npout3 = torch.tensor(output3[1][0]).numpy()
npout4 = torch.tensor(output4[1][0]).numpy()

C:\Users\LI\AppData\Local\Temp\ipykernel_16044\2685113588.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  npout1 = torch.tensor(output1[1][0]).numpy()
C:\Users\LI\AppData\Local\Temp\ipykernel_16044\2685113588.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  npout2 = torch.tensor(output2[1][0]).numpy()
C:\Users\LI\AppData\Local\Temp\ipykernel_16044\2685113588.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  npout3 = torch.tensor(output3[1][0]).numpy()
C:\Users\LI\AppData\Local\Temp\ipykernel_16044\2685113588.py:18: UserWarning

In [41]:
vectors_matrix1 = np.array([npout1, npout2])

similarity_matrix1 = cosine_similarity(vectors_matrix1)

print("Cosine Similarity Matrix:")
print(similarity_matrix1)

Cosine Similarity Matrix:
[[1.         0.27657366]
 [0.27657366 0.99999976]]


In [42]:
vectors_matrix1 = np.array([npout1, npout3])

similarity_matrix1 = cosine_similarity(vectors_matrix1)

print("Cosine Similarity Matrix:")
print(similarity_matrix1)

Cosine Similarity Matrix:
[[1.         0.19013044]
 [0.19013044 0.99999976]]


In [43]:
vectors_matrix1 = np.array([npout1, npout4])

similarity_matrix1 = cosine_similarity(vectors_matrix1)

print("Cosine Similarity Matrix:")
print(similarity_matrix1)

Cosine Similarity Matrix:
[[1.        0.9770721]
 [0.9770721 0.9999999]]
