META LASER: https://github.com/facebookresearch/LASER

Notes: pretty bad at recognizing negatives.

In [2]:
# shell

# export LASER="/mnt/c/Users/LI/Desktop/UNIWORK/MASTERS/THESIS/misinfo-eng-est/models/laser2"
# bash ./models/embed.sh ./models/input.txt ./models/output.bin

In [4]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

dim = 1024
X = np.fromfile("./output.bin", dtype=np.float32, count=-1)                                                     
X.resize(X.shape[0] // dim, dim)   

In [5]:
# Ginger helps cure cancer. + Ingver aitab ravida vähki.

vectors_matrix1 = np.array([X[0], X[1]])

similarity_matrix1 = cosine_similarity(vectors_matrix1)

print("Cosine Similarity Matrix:")
print(similarity_matrix1)

Cosine Similarity Matrix:
[[1.         0.84908056]
 [0.84908056 1.0000001 ]]


In [6]:
# Ginger helps cure cancer. + Ingver ei aita ravida vähki.

vectors_matrix2 = np.array([X[0], X[2]])

similarity_matrix2 = cosine_similarity(vectors_matrix2)

print("Cosine Similarity Matrix:")
print(similarity_matrix2)

Cosine Similarity Matrix:
[[1.        0.8227463]
 [0.8227463 1.       ]]


Additional testing with paragraphs.

In [24]:
# import pandas as pd
# snippet = pd.read_csv('../est-dataset/news_data.csv').iloc[10]['Text']
# bash ./models/embed.sh ./models/input.txt ./models/output.bin

In [28]:
# first paragraph from snippet
# second, snippet translated to eng
# third, eng snippet text shuffled
# fourth, unrelated parangraph

dim = 1024
X = np.fromfile("./output.bin", dtype=np.float32, count=-1)                                                     
X.resize(X.shape[0] // dim, dim)   

In [29]:
vectors_matrix1 = np.array([X[0], X[1]])

similarity_matrix1 = cosine_similarity(vectors_matrix1)

print("Cosine Similarity Matrix:")
print(similarity_matrix1)

Cosine Similarity Matrix:
[[1.0000001 0.9743799]
 [0.9743799 1.0000002]]


In [30]:
vectors_matrix2 = np.array([X[0], X[2]])

similarity_matrix2 = cosine_similarity(vectors_matrix2)

print("Cosine Similarity Matrix:")
print(similarity_matrix2)

Cosine Similarity Matrix:
[[1.0000001 0.9589337]
 [0.9589337 1.0000001]]


In [31]:
vectors_matrix3 = np.array([X[0], X[3]])

similarity_matrix3 = cosine_similarity(vectors_matrix3)

print("Cosine Similarity Matrix:")
print(similarity_matrix3)

# how???

Cosine Similarity Matrix:
[[1.0000001  0.8660779 ]
 [0.8660779  0.99999994]]
